# Generated by Django 2.0 on 2022-04-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('nickname', models.CharField(max_length=128)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.PositiveIntegerField(choices=[(1, 'normal'), (0, 'deleted')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
